# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myblog', '0016_auto_20161209_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='ALBUM', max_length=20, verbose_name='\u76f8\u518c\u540d')),
                ('Create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u5efa\u518c\u65f6\u95f4')),
                ('Revise_date', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Albums', to='myblog.Blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='PHOTO', max_length=20, verbose_name='\u7167\u7247\u540d')),
                ('Image', models.ImageField(upload_to='img/photo')),
                ('Album', models.ManyToManyField(related_name='Photos', to='photo.Album')),
            ],
        ),
    ]
