# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='img/photo/thumbnail'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Image',
            field=models.ImageField(default='../static/photo/image/default.jpg', upload_to='img/photo'),
        ),
    ]
