# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161216_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Image',
            new_name='Orig_photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='Thumbnail',
            new_name='Thumbnail_photo',
        ),
    ]
